language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external
branches:
  except:
    - master
after_success:
  - git clone https://$GITHUB_REPO
  - cd $(basename ${GITHUB_REPO%.git})
  - git config user.name "Travis CI"
  - git config user.email ${EMAIL}
  - rsync -az --delete --exclude '.git*' ../_site/ .
  - touch .nojekyll
  - git add -A .
  - git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
  - git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GITHUB_REPO: github.com/hugoleodev/hugoleodev.github.io.git
    - REPO_TARGET_BRANCH: master
    - secure: OfWAvI0aOlDmgGX4pQbVYDKgcqeV8wVwmWQfyoM10wLkEbu7v83e15C1xRmNJGCdwmgzvwuNH/0nhhDZDbgCHZcBhhss1lgMfH/CZruDyrbY2kmd4G5F71Sn89mNwgChaA/lLxcRfR/GJ2PdrZS+LaBnhHcjBh208DfO8KUu9qP038NITXXBHGFf06r9Fn1BbhfGlJK2aWsalY7bLYIxHq06dVC3PDGP9ZT+dvqfew9xryJ0N5dT8DX/pCuuCl+19OTfHj/7UyKUgntZGp8wTKXDTrtJiYyJ+PKmSwt2lk/7CV0Ve62Kgx1LzB2QAO5MuanuXcwMR8wj2G8PAYcrACzCtcRIYmfwCQMCGbMrHcOI96LUoAM0ZkWWwTO0OJIPv7bOyvRBV47CWp2Oq3dmYHVcaik1dME/tpNE0u/Im2zqTW1F8G4pKS8ebItNuNd+fIJSA0MemfKS0UtLxdOXzgPIHyxbGHXu/vlsmKsBHUY2L3hlqjr0p7LBdjJ+sxs87f8Xk9uXebOgzmwP+98/Y8vBi1u9V7Hglf5YGLo3myfwLjHqD0SOZ8wXVEFtRn6MK0/WUAlOPxaamk0TP+TwSpPoDKec8NUmEl/Z+Y4pC11KL+sIWor1JDhDDMDYjcAPXc6rt35fNy2wGX/1W+RKaWrsm7Ez8fpi0wXM7ls9/LA=
    - secure: XLgtL2thZ0bJqSmI7j/1W59Awyv9d7L5+VNUqdwzjNC5ZZMa9gyc7KKJRMHraMBDG9bgeZsPuUWfmi/AiPVDNMT+pkTfQoI+N/9ef25DAa7vTzdo6devHaZcZmi9bewVFql/KAvb2rCFLDXZ++PclVlrXFyL6isZNUDQSTo+0OJueOMAnU5wHC8rwWUdCNzrAOF8Mn5f0G3pxZj+pK+QN+tPKE9nQm7Q/iqusq324/oeF+nWF7D5nqZrePEt7jm0zY4aoB0wRj0W32ZKpDjndmHyU6nM6MdsXhWUo2p+9OLPl+R9fxK+YsFiNYlD1dInxc/krky3wcAWoLBJvqgbKaFo1uIiZyR4eas4DI4A58SMsP6JMd4yhv6aeo+213rm0CeFIe1aS5XDb3p2P9Q2qJvg7eh9Il/HiNgbzB/KQ31jrZunCOBXFcK+8mMERsW7x3oOGz3TdVuG1PKy5bn+RBIcqYC0Y8DmAS64SuTOHZRmkmXRxeAYdO7Bx2IpbNrRj36j/+9nT9iMPLBdXgWmwAj3pEBZx2Ib9IKwzH+PrPqvfbA7WybDQg/7ttPPOp3ZgoB/aIvbI/l5Fi9Arl5sXd5Y8tmnqY0ARFp1ndGwn+yVM8YFBcaBFNJs6MzSsiJJwqVBarMKhPU8FmwXwVD1Q1N0Ue5xxkehNsPuLo0BD3A=
